name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
jobs:
  e2e:
    name: E2E Tests
    timeout-minutes: 10
    runs-on: ubuntu-latest
    env:
      CARD_NUMBER: ${{ secrets.CARD_NUMBER }}
      CARD_DATE: ${{ secrets.CARD_DATE }}
      CARD_CVV: ${{ secrets.CARD_CVV }}
      NEW_USER_1_EMAIL: ${{ secrets.NEW_USER_1_EMAIL }}
      NEW_USER_1_PASSWORD: ${{ secrets.NEW_USER_1_PASSWORD }}
      UI_BASE_URL: ${{ secrets.UI_BASE_URL }}
    steps:
    - uses: actions/checkout@v4
    - uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest
    - name: Install dependencies
      run: bun install --frozen-lockfile
    - name: Install Playwright Browsers
      run: bunx playwright install --with-deps chromium
    - name: Run E2E
      run: bun run ui-e2e
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report-e2e
        path: playwright-report/
        retention-days: 5

  api:
    name: API Tests
    timeout-minutes: 10
    runs-on: ubuntu-latest
    env:
      API_BASE_URL: ${{ secrets.API_BASE_URL }}
    steps:
    - uses: actions/checkout@v4
    - uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest
    - name: Install dependencies
      run: bun install --frozen-lockfile
    - name: Run API
      run: bun run api
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report-api
        path: playwright-report/
        retention-days: 5
